@startuml
title: All schemas
footer: Common Gateway Plugin | Commongateway | Openindex 
header: Schema
class MetadataTOOIWoo-verzoekenen-besluiten {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + datumBesluit: string
  + datumOntvangst: string
  + termijnoverschrijding: string
  + values: array
}
class MetadataTOOIbeschikkingen {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIvergaderstukkendecentraleoverheden {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIwettenenalgemeenverbindendevoorschriften {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class Index {
  + id: string
  + title: string
  + summary: string
  + description: string
  + image: string
  + url: string
  + status: integer
  + organization: object
}
class Theme {
  + id: string
  + title: string
  + summary: string
  + description: string
  + image: string
  + publications: integer
}
class Organization {
  + id: string
  + title: string
  + summary: string
  + description: string
  + image: string
  + oin: string
  + tooi: string
  + rsin: string
  + name: string
}
class MetadataTOOIklachtoordelen {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + datumBesluit: string
  + datumOntvangst: string
  + termijnoverschrijding: string
  + organisatieonderdeel: string
  + functiebenaming: string
  + gedraging: string
  + bevindingen: string
  + oordeel: string
  + conclusies: string
  + values: array
}
class MetadataTOOIsubsidieverplichtingenandersdanmetbeschikking {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIontwerpenvanwet-enregelgevingmetadviesaanvraag {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIoverigebesluitenvanalgemenestrekking {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIbijvertegenwoordigendeorganeningekomenstukken {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIbereikbaarheidsgegevens {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIagenda’senbesluitenlijstenbestuurscolleges {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class Publication {
  + id: string
  + reference: string
  + title: string
  + summary: string
  + description: string
  + image: string
  + category: string
  + portal: string
  + publicationDate: string
  + featured: boolean
  + organization: object
  + schema: string
  + status: string
  + attachments: array
  + attachment_count: integer
  + themes: array
  + data: object
  + anonymization: object
  + language: object
}
class Attachment {
  + id: string
  + reference: string
  + title: string
  + summary: string
  + description: string
  + labels: array
  + url: string
  + content: string
  + type: string
  + extension: string
  + size: integer
  + anonymization: object
  + language: object
  + version_of: string
  + hash: string
}
class MetadataTOOIorganisatieenwerkwijze {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataOpenCatalogiPubliccode {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + oprdachtgever: string
  + onderdeelTaak: string
  + onderwerp: string
  + feitelijkMateriaal: boolean
  + values: array
}
class MetadataTOOIconvenanten {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIonderzoeksrapporten {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIjaarplannenenjaarverslagen {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIadviezen {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + oprdachtgever: string
  + onderdeelTaak: string
  + onderwerp: string
  + feitelijkMateriaal: boolean
  + values: array
}
class MetadataOpenCatalogiPubliccode {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + oprdachtgever: string
  + onderdeelTaak: string
  + onderwerp: string
  + feitelijkMateriaal: boolean
  + values: array
}
class MetadataTOOIvergaderstukkenStaten-Generaal {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
@enduml
