@startuml
title: All schemas
footer: Common Gateway Plugin | Commongateway | Openindex 
header: Schema
class MetadataTOOIwettenenalgemeenverbindendevoorschriften {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataOpenCatalogiPubliccode {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + oprdachtgever: string
  + onderdeelTaak: string
  + onderwerp: string
  + feitelijkMateriaal: boolean
  + values: array
}
class Publicatie {
  + id: string
  + titel: string
  + samenvatting: string
  + beschrijving: string
  + afbeelding: string
  + categorie: string
  + portal: string
  + publicatiedatum: string
  + featured: boolean
  + organisatie: object
  + schema: string
  + bijlagen: array
  + onderwerp: object
  + data: object
}
class MetadataTOOIontwerpenvanwet-enregelgevingmetadviesaanvraag {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIvergaderstukkendecentraleoverheden {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIbijvertegenwoordigendeorganeningekomenstukken {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class Thema {
  + id: string
  + titel: string
  + samenvatting: string
  + beschrijving: string
  + afbeelding: string
  + publicaties: integer
}
class MetadataOpenCatalogiPubliccode {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + oprdachtgever: string
  + onderdeelTaak: string
  + onderwerp: string
  + feitelijkMateriaal: boolean
  + values: array
}
class MetadataTOOIoverigebesluitenvanalgemenestrekking {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIonderzoeksrapporten {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIconvenanten {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class Index {
  + id: string
  + titel: string
  + samenvatting: string
  + beschrijving: string
  + afbeelding: string
  + url: string
  + status: integer
  + organisatie: object
}
class MetadataTOOIklachtoordelen {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + datumBesluit: string
  + datumOntvangst: string
  + termijnoverschrijding: string
  + organisatieonderdeel: string
  + functiebenaming: string
  + gedraging: string
  + bevindingen: string
  + oordeel: string
  + conclusies: string
  + values: array
}
class MetadataTOOIvergaderstukkenStaten-Generaal {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class Organisatie {
  + id: string
  + titel: string
  + samenvatting: string
  + beschrijving: string
  + afbeelding: string
  + uuid: string
  + oin: string
  + tooi: string
  + rsin: string
  + naam: string
}
class Bijlage {
  + id: string
  + titel: string
  + samenvatting: string
  + beschrijving: string
  + labels: array
  + url: string
  + documentText: string
  + type: string
  + extension: string
  + size: integer
}
class MetadataTOOIagenda’senbesluitenlijstenbestuurscolleges {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIbereikbaarheidsgegevens {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIbeschikkingen {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIjaarplannenenjaarverslagen {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIWoo-verzoekenen-besluiten {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + datumBesluit: string
  + datumOntvangst: string
  + termijnoverschrijding: string
  + values: array
}
class MetadataTOOIorganisatieenwerkwijze {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
class MetadataTOOIadviezen {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + oprdachtgever: string
  + onderdeelTaak: string
  + onderwerp: string
  + feitelijkMateriaal: boolean
  + values: array
}
class MetadataTOOIsubsidieverplichtingenandersdanmetbeschikking {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
@enduml
