@startuml
title: Attachment
footer: Common Gateway Plugin | Commongateway | Openindex 
header: Schema

class Attachment {
  + id: string
  + reference: string
  + title: string
  + summary: string
  + description: string
  + labels: array
  + url: string
  + content: string
  + type: string
  + extension: string
  + size: integer
  + anonymization: object
  + language: object
  + version_of: string
  + hash: string
}
@enduml
