@startuml
title: Attachment
footer: Common Gateway Plugin | Commongateway | Openindex 
header: Schema

class Attachment {
  + id: string
  + title: string
  + summary: string
  + description: string
  + labels: array
  + url: string
  + documentText: string
  + type: string
  + extension: string
  + size: integer
}
@enduml
