@startuml
title: Attachment
footer: Common Gateway Plugin | Commongateway | Openindex 
header: Schema

class Attachment {
  + id: string
  + reference: string
  + title: string
  + summary: string
  + description: string
  + labels: array
  + accessURL: string
  + downloadURL: string
  + type: string
  + extension: string
  + size: integer
  + anonymization: object
  + languageObject: object
  + version_of: string
  + hash: string
  + published: string
  + modified: string
  + license: string
}
@enduml
