@startuml
title: Bijlage
footer: Common Gateway Plugin | Commongateway | Openindex 
header: Schema

class Bijlage {
  + id: string
  + titel: string
  + samenvatting: string
  + beschrijving: string
  + labels: array
  + url: string
  + documentText: string
  + type: string
  + extension: string
  + size: integer
}
@enduml
