@startuml
title: MetadataTOOIconvenanten
footer: Common Gateway Plugin | Commongateway | Openindex 
header: Schema

class MetadataTOOIconvenanten {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
@enduml
