@startuml
title: MetadataTOOIklachtoordelen
footer: Common Gateway Plugin | Commongateway | Openindex 
header: Schema

class MetadataTOOIklachtoordelen {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + datumBesluit: string
  + datumOntvangst: string
  + termijnoverschrijding: string
  + organisatieonderdeel: string
  + functiebenaming: string
  + gedraging: string
  + bevindingen: string
  + oordeel: string
  + conclusies: string
  + values: array
}
@enduml
