@startuml
title: MetadataTOOIWoo-verzoekenen-besluiten
footer: Common Gateway Plugin | Commongateway | Openindex 
header: Schema

class MetadataTOOIWoo-verzoekenen-besluiten {
  + tooiCategorieNaam: string
  + tooiCategorieId: string
  + tooiCategorieUri: string
  + tooiThemaNaam: string
  + tooiThemaId: string
  + tooiThemaUri: string
  + values: array
}
@enduml
