@startuml
title: MetadataWooVerzoek
footer: Common Gateway Plugin | Commongateway | Openindex 
header: Schema

class MetadataWooVerzoek {
  + id: string
  + titel: string
  + samenvatting: string
  + beschrijving: string
  + afbeelding: string
  + publicaties: integer
}
@enduml
