@startuml
title: Onderwerp
footer: Common Gateway Plugin | Commongateway | Openindex 
header: Schema

class Onderwerp {
  + id: string
  + titel: string
  + samenvatting: string
  + beschrijving: string
  + afbeelding: string
  + publicaties: integer
}
@enduml
