@startuml
title: Organization
footer: Common Gateway Plugin | Commongateway | Openindex 
header: Schema

class Organization {
  + id: string
  + title: string
  + summary: string
  + description: string
  + image: string
  + oin: string
  + tooi: string
  + rsin: string
}
@enduml
