@startuml
title: Organisatie
footer: Common Gateway Plugin | Commongateway | Openindex 
header: Schema

class Organisatie {
  + id: string
  + titel: string
  + samenvatting: string
  + beschrijving: string
  + afbeelding: string
  + uuid: string
  + oin: string
  + tooi: string
  + rsin: string
  + naam: string
}
@enduml
