@startuml
title: Publicatie
footer: Common Gateway Plugin | Commongateway | Openindex 
header: Schema

class Publicatie {
  + id: string
  + titel: string
  + samenvatting: string
  + beschrijving: string
  + afbeelding: string
  + categorie: string
  + portal: string
  + publicatiedatum: string
  + featured: boolean
  + organisatie: object
  + metadata: string
  + bijlagen: array
  + onderwerp: object
  + data: object
}
@enduml
