@startuml
title: Publication
footer: Common Gateway Plugin | Commongateway | Openindex 
header: Schema

class Publication {
  + id: string
  + reference: string
  + title: string
  + summary: string
  + description: string
  + image: string
  + category: string
  + portal: string
  + publicationDate: string
  + featured: boolean
  + organization: object
  + schema: string
  + status: string
  + attachments: array
  + attachment_count: integer
  + themes: array
  + data: array
  + anonymization: object
  + languageObject: object
  + published: string
  + modified: string
  + license: string
}
@enduml
