@startuml
title: Publication
footer: Common Gateway Plugin | Commongateway | Openindex 
header: Schema

class Publication {
  + id: string
  + title: string
  + summary: string
  + description: string
  + image: string
  + category: string
  + portal: string
  + publicationDate: string
  + featured: boolean
  + organization: object
  + schema: string
  + attachments: array
  + themes: array
  + data: array
}
@enduml
