@startuml
title: Theme
footer: Common Gateway Plugin | Commongateway | Openindex 
header: Schema

class Theme {
  + id: string
  + title: string
  + summary: string
  + description: string
  + image: string
  + publications: integer
}
@enduml
