name: Generate publiccode.yaml and .env files

# Controls when the workflow will run
on:
  push: # Trigger on any push

permissions:
  contents: write

# Uses the default file creation workflow from https://github.com/CommonGateway/workflows 
jobs:
  call-file-creation-workflow-from-default-workflows:
    uses: CommonGateway/workflows/.github/workflows/generateFilesForBundle.yml@main